version: '2'
services:
  pricetracker-app:
    image: thabomogaswa.azurecr.io/mweb-price-tracker:177
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://pricetracker-mysql:3306/pricetracker?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  pricetracker-mysql:
    extends:
      file: mysql.yml
      service: pricetracker-mysql
